catalog/urls.py
from django.conf.urls import include, url

from . import views


urlpatterns = [

    #url('', views.index, name='index'),
    url(r'^$', views.index, name='index'),
    url(r'books/$', views.BookListView.as_view(), name='books'),
    #url('book/<int:pk>', views.BookDetailView.as_view(), name='book-detail'),
    url(r'book/(?P<pk>[\w\-]+)$', views.BookDetailView.as_view(), name='book-detail'),
    url(r'authors', views.AuthorListView.as_view(), name='authors'),
    url(r'author/(?P<pk>[\w\-]+)$', views.AuthorDetailView.as_view(), name='author-detail'),
    url(r'mybooks', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
    url(r'borrowed', views.LoanedBooksAllListView.as_view(), name='all-borrowed'),
    url(r'book/(?P<pk>[-\w]+)/renew/$', views.renew_book_librarian, name='renew-book-librarian'),
    url(r'^author/create/$', views.AuthorCreate.as_view(), name='author-create'),
    url(r'^author/(?P<pk>\d+)/update/$', views.AuthorUpdate.as_view(), name='author-update'),
    url(r'^author/(?P<pk>\d+)/delete/$', views.AuthorDelete.as_view(), name='author-delete'),
    url(r'^book/create/$', views.BookCreate.as_view(), name='book-create'),
    url(r'^book/(?P<pk>\d+)/update/$', views.BookUpdate.as_view(), name='book-update'),
    url(r'^book/(?P<pk>\d+)/delete/$', views.BookDelete.as_view(), name='book-delete'),
]

locallibrary/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin

from django.views.generic import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    # Maps any urls starting with catalog
    # to be handled by the catalog app
    url('catalog/', include('catalog.urls')),

    #Maps the root URL and redirect to /catalog/
    url(r'^$', RedirectView.as_view(url='/catalog/', permanent=True)),

    #Add Django site authentication urls (for login, logout, password management)
    url(r'^accounts/', include('django.contrib.auth.urls')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

catalog/models.py
from django.db import models
from django.urls import reverse #Used to generate URLs by reversing the URL patterns

from django.core.urlresolvers import reverse

import uuid # Required for unique book instances
from datetime import date

from django.contrib.auth.models import User

# Create your models here.

class Genre(models.Model):
    #Model representing a book genre (e.g. Science Fiction, Non Fiction).

    name = models.CharField(max_length=200, help_text="Enter a book genre\
         (e.g. Science Fiction, Militar history etc.)")

    def __str__(self):
        # String for representing the Model object (in Admin site etc.)

        return self.name


class Language(models.Model):
    """
    Model representing a Language (e.g. English, French, Japanese, etc.)
    """
    name = models.CharField(max_length=200, help_text="Enter a the book's\
         natural language (e.g. English, Spanish, Japanese etc.)")

    def __str__(self):
        """
        String for representing the Model object (in Admin site etc.)
        """
        return self.name


class Book(models.Model):
    """
    Model representing a book (but not a specific copy of a book).
    """
    title = models.CharField(max_length=200)
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    # Foreign Key used because book can only have one author, but authors can have multiple books
    # In practice a book might have multiple authors, but not in this implementation!
    # Author as a string rather than object because it hasn't been declared yet in the file.
    # null=True, which allows the database to store a Null value if no author is selected,
    # and on_delete=models.SET_NULL, which will set the value of the author to
    # Null if the associated author record is deleted.


    summary = models.TextField(max_length=1000, help_text="Enter a brief\
         description of the book")
    isbn = models.CharField('ISBN', max_length=13, help_text="13 Character\
         <a href='https://www.isbn-international.org/content/what-isbn'>ISBN number</a>")

    genre = models.ManyToManyField(Genre, help_text="Select a genre for this book")
    # ManyToManyField used because genre can contain many books. Books can
    # cover many genres. Genre class has already been defined so we can specify
    # the object above.

    language = models.ForeignKey('Language', on_delete=models.SET_NULL, null=True)

    def __str__(self):
        """
        String for representing the Model object.
        """
        return self.title

    def get_absolute_url(self):
        """
        Returns the url to access a particular book instance.
        """
        return reverse('book-detail', args=[str(self.id)])


    def display_genre(self):
        """
        Creates a string for the Genre. This is required to display genre in Admin.
        """
        return ',   '.join([ genre.name for genre in self.genre.all()[:3] ])
    display_genre.short_description  = 'Genre'


class BookInstance(models.Model):
    """
    Model representing a specific copy of a book (i.e. that can be borrowed
    from the library).
    """

    # This type of field allocates a globally unique value for each instance
    # (one for every book you can find in the library).
    id = models.UUIDField(primary_key=True, default=uuid.uuid4,
         help_text="Unique ID for this particular book across whole library")

    # A book can have multiple bookinstances
    book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True)
    imprint = models.CharField(max_length=200)

    # Date at which the book is expected to come
    # available after being borrowed or in maintenance).
    due_back = models.DateField(null=True, blank=True)

     # Deudor
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)


    @property
    def is_overdue(self):
        # Tell if a particular book instance is overdue (Atrasado)

        if self.due_back and date.today() > self.due_back:
            return True
        return False


    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(max_length=1, choices=LOAN_STATUS, blank=True,
        default='m', help_text="Book availability")

    class Meta:
        ordering = ["due_back"]

        # Define a permission to allow a user to mark that a book has been returned
        permissions = (("can_mark_returned", "Set book as returned"),)

    def __str__(self):
        """
        String for representing the Model object
        """

        #return '%s (%s)' % (self.id, self.book.title)
        return '{0} ({1})'.format(self.id, self.book.title)
        #return '{0}'.format(self.id)



class Author(models.Model):
    """
    Model representing an author.
    """
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)

    def get_absolute_url(self):
        """
        Returns the url to access a particular author instance.
        """
        return reverse('author-detail', args=[str(self.id)])


    def __str__(self):
        """
        String for representing the Model object.
        """
        #return '%s, %s' % (self.last_name, self.first_name)
        return '{0}, {1}'.format(self.last_name, self.first_name)

catalog/forms.py
from django import forms
from django.core.exceptions import ValidationError

 # ugettext_lazy is a Django's translation functions
from django.utils.translation import ugettext_lazy as _

import datetime # For checking renewal date range.

class RenewBookForm(forms.Form):
    renewal_date = forms.DateField(help_text="Enter a date between now and 4\
         weeks (default 3).")

    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']

        # Check date is not in past.
        if data < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'))

        # Check date is in range librarian allowed to change (+4 weeks).
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_('Invalid date - renewal more than 4 weeks ahead'))

        # Always return the cleaned data.
        return data



""" Form example using ModelForm
from django.forms import ModelForm
from .models import BookInstance

class RenewBookModelForm(ModelForm):

    def clean_due_back(self):
        data = self.cleaned_data['due_back']

        # Check data is not in past
        if data < datetime.date.today():
           raise ValidationError(_('Invalid date - renewal in past'))

        #Check date is in range librarian allowed to change (+4 weeks)
       if data > datetime.date.today() + datetime.timedelta(weeks=4):
           raise ValidationError(_('Invalid date - renewal more than 4 weeks ahead'))

        #Always return the cleaned data.
        return data

    class Meta:
        model = BookInstance

        # List of the model fields to include in the form
        # (It can include all fields using fields = '__all__')
        fields = ['due_back',]
        labels = { 'due_back': _('Renewal date'), }
        help_texts = { 'due_back': _('Enter a date between now and 4 weeks (default 3).'), }
"""

catalog/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse, reverse_lazy

from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.decorators import permission_required

import datetime

from .models import Book, Author, BookInstance, Genre
from .forms import RenewBookForm


def index(request):
    """
    View function for home page of site.
    """
    # Generate counts of some of the main objects
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()

    #Available books (status = 'a')
    num_instances_available = BookInstance.objects.filter(status__exact='a').count()
    num_authors = Author.objects.count() # The 'all()' is implied by default

    # Number of visits to this view, as counted in the session variable.
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1

    context_dict = {'num_books': num_books, 'num_instances': num_instances}
    context_dict['num_instances_available'] = num_instances_available
    context_dict['num_authors'] = num_authors
    context_dict['num_visits'] = num_visits

    return render(request, 'index.html', context_dict)


class BookListView(generic.ListView):
    """
    Generic class-based view for a list of books.
    """
    model = Book
    paginate_by = 3

    # Name for the list as a template variable
    # By defect is the model name and '_list' or 'object_list'
    #context_object_name = 'my_book_list'

    # Get 5 books containing the title war
    #queryset = Book.objects.filter(title__icontains='war')[:5]

    # Specify the template name/location.
    # By defect is the model name and '_list.html'
    template_name = 'catalog/book_list.html'


class BookDetailView(generic.DetailView):
    """
    Generic class-based detail view for a book.
    """
    model = Book


class AuthorListView(generic.ListView):
    """
    Generic class-based view for a list of authors.
    """
    model = Author
    paginate_by = 3


class AuthorDetailView(generic.DetailView):

    model = Author


class LoanedBooksByUserListView(LoginRequiredMixin, generic.ListView):
    """
    Generic class-based view listing books on loan to current user.
    """
    template_name = 'catalog/bookinstance_list_borrowed_user.html'
    model = BookInstance
    paginate_by = 2

    def get_queryset(self):
        return BookInstance.objects.filter(borrower=self.request.user).filter(
            status__exact='o').order_by('due_back')


class LoanedBooksAllListView(PermissionRequiredMixin, generic.ListView):
    """
    Generic class-based view listing all books on loan.
    Only visible to users with can_mark_returned permission.
    """
    model = BookInstance
    permission_required = 'catalog.can_mark_returned'
    template_name ='catalog/bookinstance_list_borrowed_all.html'
    paginate_by = 2

    def get_queryset(self):
        return BookInstance.objects.filter(status__exact='o').order_by('due_back')


@permission_required('catalog.can_mark_returned')
def renew_book_librarian(request, pk):
    """
    View function for renewing a specific BookInstance by librarian
    """
    book_inst = get_object_or_404(BookInstance, pk=pk)

    # If this is a POST request then process the Form data
    if request.method == 'POST':

        # Create a form instance and populate it with data from the request (binding):
        form = RenewBookForm(request.POST)

        # Check if the form is valid
        if form.is_valid():
            # Procces the data in form.cleaned_data as required
            # (here we just write it to the model due_back field)
            book_inst.due_back = form.cleaned_data['renewal_date']
            book_inst.save()

            # Redirect to a new URL
            return HttpResponseRedirect(reverse('all-borrowed'))

    # If this is a GET (or any other method) create the default form.
    else:
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
        form = RenewBookForm(initial={'renewal_date': proposed_renewal_date,})

    return render(request, 'catalog/book_renew_librarian.html', {'form': form, 'bookinst': book_inst})


class AuthorCreate(PermissionRequiredMixin, CreateView):
    model = Author
    fields = '__all__'
    initial = {'date_of_birth' : '05/01/2018', }
    permission_required = 'catalog.can_mark_returned'


class AuthorUpdate(PermissionRequiredMixin, UpdateView):
    model = Author
    fields = {'first_name', 'last_name', 'date_of_birth', 'date_of_death'}
    permission_required = 'catalog.can_mark_returned'


class AuthorDelete(PermissionRequiredMixin, DeleteView):
    model = Author
    permission_required = 'catalog.can_mark_returned'

    # Method 1
    #sucess_url = reverse_lazy('authors')

    # Method 2:
    def get_success_url(self):
        return reverse('authors')


class BookCreate(PermissionRequiredMixin, CreateView):
    model = Book
    fields = '__all__'
    permission_required = 'catalog.can_mark_returned'


class BookUpdate(PermissionRequiredMixin, UpdateView):
    model = Book
    fields = '__all__'
    permission_required = 'catalog.can_mark_returned'


class BookDelete(PermissionRequiredMixin, DeleteView):
    model = Book
    permission_required = 'catalog.can_mark_returned'

    def get_sucess_url(self):
        return reverse('books')

catalog/templates/catalog/author_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}
     <br>
    <h1>Delete Author</h1>

    <p>Are you sure  you want to delete the author <strong>{{ author }}</strong>?</p>

    <form action="" method="POST">
        {% csrf_token %}
        <input  type="submit" action="" class="btn btn-danger" value="Yes, delete"/>
    </form>

{% endblock %}

catalog/templates/catalog/author_detail.html
{% extends "base_generic.html" %}

{% block content %}

    <h1>Author: {{ author }} </h1>
    <p>
        {% if author.date_of_birth %}
            {{author.date_of_birth}} -
        {% endif %}
        {% if author.date_of_death %}
            {{author.date_of_death}}
        {% endif %}
    </p>
    <p>
        {% if perms.catalog.can_mark_returned  %}
            <a href="{% url 'author-update' author.pk %}" class="btn btn-primary">Update Author</a>
            <a href="{% url 'author-delete' author.pk %}" class="btn btn-warning">Delete Author</a>
        {% endif %}
    </p>
    <div style="margin-left:20px;margin-top:20px">
        <h3>Books</h3>

        <dl>
        {% for book in author.book_set.all %}
          <dt>
            <a href="{% url 'book-detail' book.pk %}">{{book}}</a>
                ({{book.bookinstance_set.all.count}})
           </dt>
          <dd>{{book.summary}}</dd><br>
        {% endfor %}
        </dl>
    </div>
{% endblock %}

catalog/templates/catalog/author_form.html
<!-- form for the AuthorCreate and AuthorUpdate views -->

{% extends "base_generic.html" %}

{% block content %}
    <br>
    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table><br>
        <input type="submit" name="Submit">
    </form>

{% endblock %}

catalog/templates/catalog/author_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Author List</h1>

    {% if author_list %}
        <ul>
            {% for author in author_list %}
                <li>
                    <a href="{{ author.get_absolute_url }}">
                        {{ author }} ({{author.date_of_birth}} -
                            {% if author.date_of_death %}
                                {{author.date_of_death}}
                            {% endif %})
                    </a>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>There are no authors available.</p>
    {% endif %}
{% endblock %}

catalog/templates/catalog/book_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}
    <br>
    <h1>Delete Book</h1>

    <p>Are you sure you want to delete the book: {{ book }}?</p>

    <form action="" method="POST">
      {% csrf_token %}
      <input type="submit" action="" class="btn btn-danger" value="Yes, delete." />
    </form>
{% endblock  %}

catalog/templates/catalog/book_detail.html
{% extends "base_generic.html" %}

{% block content %}

    <h1>Title: {{ book.title }}</h1>
    <p><strong>Author: </strong><a href="{% url 'author-detail' book.author.pk %}">{{ book.author }}</a></p>
    <p><strong>Summary: </strong>{{ book.summary }}</p>
    <p><strong>ISBN: </strong> {{ book.isbn }}</p>
    <p><strong>Language: </strong> {{ book.language }}</p>
    <p><strong>Genre:</strong>
        {% for genre in book.genre.all %}
                {{ genre }}
            {% if not forloop.last %}
                ,
            {% endif %}
        {% endfor %}
    </p>

    <div style="margin-left:20px;margin-top:20px">
    <h4>Copies</h4>

    <!-- bookinstance_set.all is a "reverse lookup" and return the set of BookInstance records
            associated with a particular Book. The name of the function is constructed by
            lower-casing the model name where the ForeignKey was declared, followed by '_set ' -->
    {% for copy in book.bookinstance_set.all %}
        <hr>

        <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger
            {% else %}text-warning{% endif %}">{{ copy.get_status_display }}</p>
            {% if copy.status != 'a' %}
                <p><strong>Due to be returned:</strong> {{copy.due_back}}</p>
            {% endif %}
                <p><strong>Imprint:</strong> {{copy.imprint}}</p>
                <p class="text-muted"><strong>Id:</strong> {{copy.id}}</p>
    {% endfor %}
    </div>
{% endblock %}

catalog/templates/catalog/book_form.html
{% extends "base_generic.html" %}

{% block content %}
    <br>
    <form action="" method="POST">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table><br>
        <input type="submit" class="btn btn-primary"  value="Confirmar">
    </form>
{% endblock %}

catalog/templates/catalog/book_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Book List</h1>

    {% if book_list %}
        <ul>
            {% for book in book_list %}
                <li>
                    <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> -  ({{ book.author }})
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>There are no books in the library.</p>
    {% endif %}
{% endblock %}

catalog/templates/catalog/book_renew_librarian.html
{% extends "base_generic.html" %}
{% block content %}

    <h1>Renew: {{bookinst.book.title}}</h1>
    <p>Borrower: {{bookinst.borrower}}</p>
    <p{% if bookinst.is_overdue %} class="text-danger"{% endif %}>
            Due date: {{bookinst.due_back}}
    </p>

    <!-- An empty action means that the form data will be posted back to the
            current URL of the page -->
    <form action="" method="post">
        {% csrf_token %}
        <table>
        {{ form }}
        </table>
        <input type="submit" value="Submit" />
    </form>

{% endblock %}

catalog/templates/catalog/bookinstance_list_borrowed_all.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>All Borrowed Books</h1>

    {% if bookinstance_list %}
    <ul>

      {% for bookinst in bookinstance_list %}
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a>
         ({{ bookinst.due_back }})
          {% if user.is_staff %}
            - {{ bookinst.borrower }}
          {% endif %}
          {% if perms.catalog.can_mark_returned %}
            | <a href="{% url 'renew-book-librarian' bookinst.id %}">Renew</a>
          {% endif %}
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no books borrowed.</p>
    {% endif %}
{% endblock %}

catalog/templates/catalog/bookinstance_list_borrowed_user.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Borrowed books</h1>

    {% if bookinstance_list %}
    <ul>

      {% for bookinst in bookinstance_list %}
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a> ({{ bookinst.due_back }})
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no books borrowed.</p>
    {% endif %}
{% endblock %}